/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo_da_memoria;

import codigo_jogo_da_memoria.Jogador;
import java.awt.Color;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.ImageIcon;

/**
 *
 * @author pedro
 */
public class DefinirDificuldade extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public DefinirDificuldade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_MenuPrincipal = new javax.swing.JPanel();
        barra_inferior = new javax.swing.JPanel();
        barra_superior = new javax.swing.JPanel();
        texto_barra_superior = new javax.swing.JLabel();
        titulo_dificuldade = new javax.swing.JLabel();
        botao_voltar = new javax.swing.JPanel();
        icone_botao_voltar = new javax.swing.JLabel();
        botao_facil = new javax.swing.JPanel();
        texto_botao_facil = new javax.swing.JLabel();
        botao_medio = new javax.swing.JPanel();
        texto_botao_medio = new javax.swing.JLabel();
        botao_dificil = new javax.swing.JPanel();
        texto_botao_dificil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Memória com elementos químicos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("janela"); // NOI18N
        setResizable(false);

        painel_MenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painel_MenuPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        barra_inferior.setBackground(new java.awt.Color(255, 255, 255));
        barra_inferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout barra_inferiorLayout = new javax.swing.GroupLayout(barra_inferior);
        barra_inferior.setLayout(barra_inferiorLayout);
        barra_inferiorLayout.setHorizontalGroup(
            barra_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        barra_inferiorLayout.setVerticalGroup(
            barra_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        barra_superior.setBackground(new java.awt.Color(255, 255, 255));
        barra_superior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        barra_superior.setToolTipText("");

        texto_barra_superior.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        texto_barra_superior.setForeground(new java.awt.Color(0, 0, 0));
        texto_barra_superior.setText("Jogo da Memória");

        javax.swing.GroupLayout barra_superiorLayout = new javax.swing.GroupLayout(barra_superior);
        barra_superior.setLayout(barra_superiorLayout);
        barra_superiorLayout.setHorizontalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        barra_superiorLayout.setVerticalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texto_barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
        );

        titulo_dificuldade.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        titulo_dificuldade.setForeground(new java.awt.Color(0, 0, 0));
        titulo_dificuldade.setText("Dificuldade");

        botao_voltar.setBackground(new java.awt.Color(255, 255, 255));
        botao_voltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botao_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_voltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_voltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_voltarMouseExited(evt);
            }
        });

        icone_botao_voltar.setIcon(new javax.swing.ImageIcon("D:\\Projetos\\jogo_da_memoria\\icones\\voltar.png")); // NOI18N

        javax.swing.GroupLayout botao_voltarLayout = new javax.swing.GroupLayout(botao_voltar);
        botao_voltar.setLayout(botao_voltarLayout);
        botao_voltarLayout.setHorizontalGroup(
            botao_voltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botao_voltarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icone_botao_voltar)
                .addContainerGap())
        );
        botao_voltarLayout.setVerticalGroup(
            botao_voltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botao_voltarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icone_botao_voltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botao_facil.setBackground(new java.awt.Color(255, 255, 255));
        botao_facil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        botao_facil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_facilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_facilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_facilMouseExited(evt);
            }
        });

        texto_botao_facil.setBackground(new java.awt.Color(0, 0, 0));
        texto_botao_facil.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        texto_botao_facil.setForeground(new java.awt.Color(0, 0, 0));
        texto_botao_facil.setText("Facil");

        javax.swing.GroupLayout botao_facilLayout = new javax.swing.GroupLayout(botao_facil);
        botao_facil.setLayout(botao_facilLayout);
        botao_facilLayout.setHorizontalGroup(
            botao_facilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botao_facilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(texto_botao_facil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botao_facilLayout.setVerticalGroup(
            botao_facilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botao_facilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_botao_facil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        botao_medio.setBackground(new java.awt.Color(255, 255, 255));
        botao_medio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        botao_medio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_medioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_medioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_medioMouseExited(evt);
            }
        });

        texto_botao_medio.setBackground(new java.awt.Color(0, 0, 0));
        texto_botao_medio.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        texto_botao_medio.setForeground(new java.awt.Color(0, 0, 0));
        texto_botao_medio.setText("Medio");

        javax.swing.GroupLayout botao_medioLayout = new javax.swing.GroupLayout(botao_medio);
        botao_medio.setLayout(botao_medioLayout);
        botao_medioLayout.setHorizontalGroup(
            botao_medioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botao_medioLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(texto_botao_medio)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        botao_medioLayout.setVerticalGroup(
            botao_medioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botao_medioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_botao_medio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        botao_dificil.setBackground(new java.awt.Color(255, 255, 255));
        botao_dificil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        botao_dificil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_dificilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_dificilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_dificilMouseExited(evt);
            }
        });

        texto_botao_dificil.setBackground(new java.awt.Color(0, 0, 0));
        texto_botao_dificil.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        texto_botao_dificil.setForeground(new java.awt.Color(0, 0, 0));
        texto_botao_dificil.setText("Dificil");

        javax.swing.GroupLayout botao_dificilLayout = new javax.swing.GroupLayout(botao_dificil);
        botao_dificil.setLayout(botao_dificilLayout);
        botao_dificilLayout.setHorizontalGroup(
            botao_dificilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botao_dificilLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(texto_botao_dificil)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        botao_dificilLayout.setVerticalGroup(
            botao_dificilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botao_dificilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_botao_dificil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout painel_MenuPrincipalLayout = new javax.swing.GroupLayout(painel_MenuPrincipal);
        painel_MenuPrincipal.setLayout(painel_MenuPrincipalLayout);
        painel_MenuPrincipalLayout.setHorizontalGroup(
            painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(barra_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(barra_inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_MenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_MenuPrincipalLayout.createSequentialGroup()
                        .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botao_dificil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botao_facil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botao_medio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(titulo_dificuldade)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(botao_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        painel_MenuPrincipalLayout.setVerticalGroup(
            painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_MenuPrincipalLayout.createSequentialGroup()
                .addComponent(barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(titulo_dificuldade)
                .addGap(69, 69, 69)
                .addComponent(botao_facil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_medio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_dificil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(barra_inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_facilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_facilMouseEntered
        botao_facil.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_botao_facilMouseEntered

    private void botao_facilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_facilMouseExited
        botao_facil.setBackground(Color.WHITE);
    }//GEN-LAST:event_botao_facilMouseExited

    private void botao_dificilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_dificilMouseEntered
        botao_dificil.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_botao_dificilMouseEntered

    private void botao_dificilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_dificilMouseExited
        botao_dificil.setBackground(Color.WHITE);
    }//GEN-LAST:event_botao_dificilMouseExited

    private void botao_medioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_medioMouseEntered
        botao_medio.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_botao_medioMouseEntered

    private void botao_medioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_medioMouseExited
        botao_medio.setBackground(Color.WHITE);
    }//GEN-LAST:event_botao_medioMouseExited

    private void botao_dificilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_dificilMouseClicked
        new LayoutDificil().setVisible(true);
        
        int[] array_cartas = {20,20,6,6,17,17,16,16,50,50,26,26,15,15,31,31,2,2,1,1,3,3,12,12,79,79,8,8,19,19,14,14,11,11,30,30};
        shuffleArray(array_cartas);
                
        LayoutDificil.label_carta_1.setIcon(new ImageIcon("icones/"+array_cartas[0]+".png"));
        LayoutDificil.label_carta_2.setIcon(new ImageIcon("icones/"+array_cartas[1]+".png"));
        LayoutDificil.label_carta_3.setIcon(new ImageIcon("icones/"+array_cartas[2]+".png"));
        LayoutDificil.label_carta_4.setIcon(new ImageIcon("icones/"+array_cartas[3]+".png"));
        LayoutDificil.label_carta_5.setIcon(new ImageIcon("icones/"+array_cartas[4]+".png"));
        LayoutDificil.label_carta_6.setIcon(new ImageIcon("icones/"+array_cartas[5]+".png"));
        LayoutDificil.label_carta_7.setIcon(new ImageIcon("icones/"+array_cartas[6]+".png"));
        LayoutDificil.label_carta_8.setIcon(new ImageIcon("icones/"+array_cartas[7]+".png"));
        LayoutDificil.label_carta_9.setIcon(new ImageIcon("icones/"+array_cartas[8]+".png"));
        LayoutDificil.label_carta_10.setIcon(new ImageIcon("icones/"+array_cartas[9]+".png"));
        LayoutDificil.label_carta_11.setIcon(new ImageIcon("icones/"+array_cartas[10]+".png"));
        LayoutDificil.label_carta_12.setIcon(new ImageIcon("icones/"+array_cartas[11]+".png"));
        LayoutDificil.label_carta_13.setIcon(new ImageIcon("icones/"+array_cartas[12]+".png"));
        LayoutDificil.label_carta_14.setIcon(new ImageIcon("icones/"+array_cartas[13]+".png"));
        LayoutDificil.label_carta_15.setIcon(new ImageIcon("icones/"+array_cartas[14]+".png"));
        LayoutDificil.label_carta_16.setIcon(new ImageIcon("icones/"+array_cartas[15]+".png"));
        LayoutDificil.label_carta_17.setIcon(new ImageIcon("icones/"+array_cartas[16]+".png"));
        LayoutDificil.label_carta_18.setIcon(new ImageIcon("icones/"+array_cartas[17]+".png"));
        LayoutDificil.label_carta_19.setIcon(new ImageIcon("icones/"+array_cartas[18]+".png"));
        LayoutDificil.label_carta_20.setIcon(new ImageIcon("icones/"+array_cartas[19]+".png"));
        LayoutDificil.label_carta_21.setIcon(new ImageIcon("icones/"+array_cartas[20]+".png"));
        LayoutDificil.label_carta_22.setIcon(new ImageIcon("icones/"+array_cartas[21]+".png"));
        LayoutDificil.label_carta_23.setIcon(new ImageIcon("icones/"+array_cartas[22]+".png"));
        LayoutDificil.label_carta_24.setIcon(new ImageIcon("icones/"+array_cartas[23]+".png"));
        LayoutDificil.label_carta_25.setIcon(new ImageIcon("icones/"+array_cartas[24]+".png"));
        LayoutDificil.label_carta_26.setIcon(new ImageIcon("icones/"+array_cartas[25]+".png"));
        LayoutDificil.label_carta_27.setIcon(new ImageIcon("icones/"+array_cartas[26]+".png"));
        LayoutDificil.label_carta_28.setIcon(new ImageIcon("icones/"+array_cartas[27]+".png"));
        LayoutDificil.label_carta_29.setIcon(new ImageIcon("icones/"+array_cartas[28]+".png"));
        LayoutDificil.label_carta_30.setIcon(new ImageIcon("icones/"+array_cartas[29]+".png"));
        LayoutDificil.label_carta_31.setIcon(new ImageIcon("icones/"+array_cartas[30]+".png"));
        LayoutDificil.label_carta_32.setIcon(new ImageIcon("icones/"+array_cartas[31]+".png"));
        LayoutDificil.label_carta_33.setIcon(new ImageIcon("icones/"+array_cartas[32]+".png"));
        LayoutDificil.label_carta_34.setIcon(new ImageIcon("icones/"+array_cartas[33]+".png"));
        LayoutDificil.label_carta_35.setIcon(new ImageIcon("icones/"+array_cartas[34]+".png"));
        LayoutDificil.label_carta_36.setIcon(new ImageIcon("icones/"+array_cartas[35]+".png"));
        
        this.dispose();
    }//GEN-LAST:event_botao_dificilMouseClicked

    private void botao_medioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_medioMouseClicked
        new LayoutMedio().setVisible(true);
        
        int[] array_cartas = {20,20,6,6,17,17,16,16,50,50,26,26,15,15,31,31,2,2,1,1,3,3,12,12,79,79,8,8,19,19,14,14,11,11,30,30};
        int[] array_medio = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
        int[] array_nums = {0,0,0,0,0,0,0,0};
        
        Random rnd = ThreadLocalRandom.current();
        
        int index = 0;
        while(index != 8){
            int pick = rnd.nextInt(array_cartas.length);
            int repete = 0;
            
            for(int k = 0; k < array_nums.length; k++){
                if(array_cartas[pick] == array_nums[k]){
                    repete = 1;
                    break;
                }
            }
            
            if(repete == 0){
                array_nums[index] = array_cartas[pick];
                index ++;
            }
            
        }
        
        array_medio[0] = array_nums[0];
        array_medio[1] = array_nums[0];
        array_medio[2] = array_nums[1];
        array_medio[3] = array_nums[1];
        array_medio[4] = array_nums[2];
        array_medio[5] = array_nums[2];
        array_medio[6] = array_nums[3];
        array_medio[7] = array_nums[3];
        array_medio[8] = array_nums[4];
        array_medio[9] = array_nums[4];
        array_medio[10] = array_nums[5];
        array_medio[11] = array_nums[5];
        array_medio[12] = array_nums[6];
        array_medio[13] = array_nums[6];
        array_medio[14] = array_nums[7];
        array_medio[15] = array_nums[7];
     
        shuffleArray(array_medio);
                
        LayoutMedio.label_carta_1.setIcon(new ImageIcon("icones/"+array_medio[0]+".png"));
        LayoutMedio.label_carta_2.setIcon(new ImageIcon("icones/"+array_medio[1]+".png"));
        LayoutMedio.label_carta_3.setIcon(new ImageIcon("icones/"+array_medio[2]+".png"));
        LayoutMedio.label_carta_4.setIcon(new ImageIcon("icones/"+array_medio[3]+".png"));
        LayoutMedio.label_carta_5.setIcon(new ImageIcon("icones/"+array_medio[4]+".png"));
        LayoutMedio.label_carta_6.setIcon(new ImageIcon("icones/"+array_medio[5]+".png"));
        LayoutMedio.label_carta_7.setIcon(new ImageIcon("icones/"+array_medio[6]+".png"));
        LayoutMedio.label_carta_8.setIcon(new ImageIcon("icones/"+array_medio[7]+".png"));
        LayoutMedio.label_carta_9.setIcon(new ImageIcon("icones/"+array_medio[8]+".png"));
        LayoutMedio.label_carta_10.setIcon(new ImageIcon("icones/"+array_medio[9]+".png"));
        LayoutMedio.label_carta_11.setIcon(new ImageIcon("icones/"+array_medio[10]+".png"));
        LayoutMedio.label_carta_12.setIcon(new ImageIcon("icones/"+array_medio[11]+".png"));
        LayoutMedio.label_carta_13.setIcon(new ImageIcon("icones/"+array_medio[12]+".png"));
        LayoutMedio.label_carta_14.setIcon(new ImageIcon("icones/"+array_medio[13]+".png"));
        LayoutMedio.label_carta_15.setIcon(new ImageIcon("icones/"+array_medio[14]+".png"));
        LayoutMedio.label_carta_16.setIcon(new ImageIcon("icones/"+array_medio[15]+".png"));
        
        this.dispose();
    }//GEN-LAST:event_botao_medioMouseClicked

    private void botao_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseClicked
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botao_voltarMouseClicked

    private void botao_voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseEntered
        botao_voltar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_botao_voltarMouseEntered

    private void botao_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_voltarMouseExited
        botao_voltar.setBackground(Color.WHITE);
    }//GEN-LAST:event_botao_voltarMouseExited

    private void botao_facilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_facilMouseClicked
        new LayoutFacil().setVisible(true);
        
        int[] array_cartas = {20,20,6,6,17,17,16,16,50,50,26,26,15,15,31,31,2,2,1,1,3,3,12,12,79,79,8,8,19,19,14,14,11,11,30,30};
        int[] array_facil = {0,0,0,0};
        
        Random rnd = ThreadLocalRandom.current();
        
        do{
            int num1 = rnd.nextInt(array_cartas.length);
            int num2 = rnd.nextInt(array_cartas.length);
            
            if(num1 != num2){
            array_facil[0] = array_cartas[num1];
            array_facil[1] = array_cartas[num1];
            array_facil[2] = array_cartas[num2];
            array_facil[3] = array_cartas[num2];
            }
          
        }while(array_facil[3] == 0);
     
        shuffleArray(array_facil);
                
        LayoutFacil.label_carta_1.setIcon(new ImageIcon("icones/"+array_facil[0]+".png"));
        LayoutFacil.label_carta_2.setIcon(new ImageIcon("icones/"+array_facil[1]+".png"));
        LayoutFacil.label_carta_3.setIcon(new ImageIcon("icones/"+array_facil[2]+".png"));
        LayoutFacil.label_carta_4.setIcon(new ImageIcon("icones/"+array_facil[3]+".png"));
        
        this.dispose();
    }//GEN-LAST:event_botao_facilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefinirDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefinirDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefinirDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefinirDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefinirDificuldade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra_inferior;
    private javax.swing.JPanel barra_superior;
    private javax.swing.JPanel botao_dificil;
    private javax.swing.JPanel botao_facil;
    private javax.swing.JPanel botao_medio;
    private javax.swing.JPanel botao_voltar;
    private javax.swing.JLabel icone_botao_voltar;
    private javax.swing.JPanel painel_MenuPrincipal;
    private javax.swing.JLabel texto_barra_superior;
    private javax.swing.JLabel texto_botao_dificil;
    private javax.swing.JLabel texto_botao_facil;
    private javax.swing.JLabel texto_botao_medio;
    private javax.swing.JLabel titulo_dificuldade;
    // End of variables declaration//GEN-END:variables

        static void shuffleArray(int[] ar)
      {
        Random rnd = ThreadLocalRandom.current();
        for (int i = ar.length - 1; i > 0; i--)
        {
          int index = rnd.nextInt(i + 1);
          // Simple swap
          int a = ar[index];
          ar[index] = ar[i];
          ar[i] = a;
        }
      }
}
