/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo_da_memoria;

import java.awt.Color;
import static java.lang.Integer.parseInt;
import static java.lang.String.valueOf;
import java.nio.file.Path;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author joaov
 */
public class LayoutFacil extends javax.swing.JFrame {
    public static int CartasSelecionadas = 0;
    public static String Path = "";
    public static String C1Icon = "";
    public static String C2Icon = "";
    public static String SegundaSelecionada = "";
    public static String PrimeiraSelecionada = "";
    public static JPanel SegundaSelecionadaObj;
    public static JPanel PrimeiraSelecionadaObj;
    public static int Pontos = 0;
    
   
    /**
     * Creates new form LayoutFacil
     */
    public LayoutFacil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_MenuPrincipal = new javax.swing.JPanel();
        barra_inferior = new javax.swing.JPanel();
        texto_pontos = new javax.swing.JLabel();
        texto_tempo_restante = new javax.swing.JLabel();
        contador_tempo = new javax.swing.JLabel();
        contador_pontos = new javax.swing.JLabel();
        barra_superior = new javax.swing.JPanel();
        texto_barra_superior = new javax.swing.JLabel();
        botao_pause = new javax.swing.JPanel();
        icone_botao_pause = new javax.swing.JLabel();
        carta_1 = new javax.swing.JPanel();
        label_carta_1 = new javax.swing.JLabel();
        carta_2 = new javax.swing.JPanel();
        label_carta_2 = new javax.swing.JLabel();
        carta_3 = new javax.swing.JPanel();
        label_carta_3 = new javax.swing.JLabel();
        carta_4 = new javax.swing.JPanel();
        label_carta_4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_MenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painel_MenuPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        barra_inferior.setBackground(new java.awt.Color(255, 255, 255));
        barra_inferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        texto_pontos.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        texto_pontos.setForeground(new java.awt.Color(0, 0, 0));
        texto_pontos.setText("Pontos: ");

        texto_tempo_restante.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        texto_tempo_restante.setForeground(new java.awt.Color(0, 0, 0));
        texto_tempo_restante.setText("Tempo restante:");

        contador_tempo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        contador_tempo.setForeground(new java.awt.Color(0, 0, 0));
        contador_tempo.setText("10");

        contador_pontos.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        contador_pontos.setForeground(new java.awt.Color(0, 0, 0));
        contador_pontos.setText("0");

        javax.swing.GroupLayout barra_inferiorLayout = new javax.swing.GroupLayout(barra_inferior);
        barra_inferior.setLayout(barra_inferiorLayout);
        barra_inferiorLayout.setHorizontalGroup(
            barra_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_inferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_pontos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contador_pontos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(texto_tempo_restante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contador_tempo)
                .addGap(123, 123, 123))
        );
        barra_inferiorLayout.setVerticalGroup(
            barra_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(texto_pontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(texto_tempo_restante)
                .addComponent(contador_tempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contador_pontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barra_superior.setBackground(new java.awt.Color(255, 255, 255));
        barra_superior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        barra_superior.setToolTipText("");

        texto_barra_superior.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        texto_barra_superior.setForeground(new java.awt.Color(0, 0, 0));
        texto_barra_superior.setText("Jogo da Memória");

        javax.swing.GroupLayout barra_superiorLayout = new javax.swing.GroupLayout(barra_superior);
        barra_superior.setLayout(barra_superiorLayout);
        barra_superiorLayout.setHorizontalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barra_superiorLayout.setVerticalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texto_barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
        );

        botao_pause.setBackground(new java.awt.Color(255, 255, 255));
        botao_pause.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botao_pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_pauseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_pauseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_pauseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botao_pauseLayout = new javax.swing.GroupLayout(botao_pause);
        botao_pause.setLayout(botao_pauseLayout);
        botao_pauseLayout.setHorizontalGroup(
            botao_pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botao_pauseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icone_botao_pause)
                .addContainerGap())
        );
        botao_pauseLayout.setVerticalGroup(
            botao_pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botao_pauseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icone_botao_pause)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        carta_1.setBackground(new java.awt.Color(255, 255, 255));
        carta_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_1Layout = new javax.swing.GroupLayout(carta_1);
        carta_1.setLayout(carta_1Layout);
        carta_1Layout.setHorizontalGroup(
            carta_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_1Layout.setVerticalGroup(
            carta_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_2.setBackground(new java.awt.Color(255, 255, 255));
        carta_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_2Layout = new javax.swing.GroupLayout(carta_2);
        carta_2.setLayout(carta_2Layout);
        carta_2Layout.setHorizontalGroup(
            carta_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_2Layout.setVerticalGroup(
            carta_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_3.setBackground(new java.awt.Color(255, 255, 255));
        carta_3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_3Layout = new javax.swing.GroupLayout(carta_3);
        carta_3.setLayout(carta_3Layout);
        carta_3Layout.setHorizontalGroup(
            carta_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_3Layout.setVerticalGroup(
            carta_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_3, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_4.setBackground(new java.awt.Color(255, 255, 255));
        carta_4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_4Layout = new javax.swing.GroupLayout(carta_4);
        carta_4.setLayout(carta_4Layout);
        carta_4Layout.setHorizontalGroup(
            carta_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_4Layout.setVerticalGroup(
            carta_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painel_MenuPrincipalLayout = new javax.swing.GroupLayout(painel_MenuPrincipal);
        painel_MenuPrincipal.setLayout(painel_MenuPrincipalLayout);
        painel_MenuPrincipalLayout.setHorizontalGroup(
            painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_MenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_pause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(barra_inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(barra_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painel_MenuPrincipalLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_MenuPrincipalLayout.setVerticalGroup(
            painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_MenuPrincipalLayout.createSequentialGroup()
                .addComponent(barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(carta_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(carta_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(botao_pause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barra_inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_pauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_pauseMouseClicked
        new MenuPause().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botao_pauseMouseClicked

    private void botao_pauseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_pauseMouseEntered
        botao_pause.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_botao_pauseMouseEntered

    private void botao_pauseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_pauseMouseExited
        botao_pause.setBackground(Color.WHITE);
    }//GEN-LAST:event_botao_pauseMouseExited

    private void carta_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_1MouseClicked
        carta_1.setName("carta_1");
        SelecionarCarta(carta_1,label_carta_1);
    }//GEN-LAST:event_carta_1MouseClicked

    private void carta_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_1MouseEntered

    }//GEN-LAST:event_carta_1MouseEntered

    private void carta_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_1MouseExited

    }//GEN-LAST:event_carta_1MouseExited

    private void carta_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_2MouseClicked
        carta_2.setName("carta_2");
        SelecionarCarta(carta_2,label_carta_2);
    }//GEN-LAST:event_carta_2MouseClicked

    private void carta_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_2MouseEntered

    }//GEN-LAST:event_carta_2MouseEntered

    private void carta_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_2MouseExited

    }//GEN-LAST:event_carta_2MouseExited

    private void carta_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_3MouseClicked
        carta_3.setName("carta_3");
        SelecionarCarta(carta_3,label_carta_3);
    }//GEN-LAST:event_carta_3MouseClicked

    private void carta_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_3MouseEntered

    }//GEN-LAST:event_carta_3MouseEntered

    private void carta_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_3MouseExited

    }//GEN-LAST:event_carta_3MouseExited

    private void carta_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_4MouseClicked
        carta_4.setName("carta_4");
        SelecionarCarta(carta_4,label_carta_4);
    }//GEN-LAST:event_carta_4MouseClicked

    private void carta_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_4MouseEntered

    }//GEN-LAST:event_carta_4MouseEntered

    private void carta_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_4MouseExited

    }//GEN-LAST:event_carta_4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutFacil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra_inferior;
    private javax.swing.JPanel barra_superior;
    private javax.swing.JPanel botao_pause;
    public static javax.swing.JPanel carta_1;
    public static javax.swing.JPanel carta_2;
    public static javax.swing.JPanel carta_3;
    public static javax.swing.JPanel carta_4;
    public static javax.swing.JLabel contador_pontos;
    private javax.swing.JLabel contador_tempo;
    private javax.swing.JLabel icone_botao_pause;
    public static javax.swing.JLabel label_carta_1;
    public static javax.swing.JLabel label_carta_2;
    public static javax.swing.JLabel label_carta_3;
    public static javax.swing.JLabel label_carta_4;
    private javax.swing.JPanel painel_MenuPrincipal;
    private javax.swing.JLabel texto_barra_superior;
    private javax.swing.JLabel texto_pontos;
    private javax.swing.JLabel texto_tempo_restante;
    // End of variables declaration//GEN-END:variables
    static void SelecionarCarta(JPanel carta,JLabel label){
        String cor_carta = carta.getBackground().toString();
        if(CartasSelecionadas == 0 && cor_carta.equals("java.awt.Color[r=255,g=255,b=255]")){
            
            Path = label.getIcon().toString();
            C1Icon = Path.substring(Path.lastIndexOf("/"  ) + 1);
            
            System.out.println("Carta 1 Selecionada!");
            carta.setBackground(Color.YELLOW);
            CartasSelecionadas ++;
            PrimeiraSelecionada = carta.getName();
            PrimeiraSelecionadaObj = carta;
            
        }else if(CartasSelecionadas == 1 && cor_carta.equals("java.awt.Color[r=255,g=255,b=255]")){
            
            SegundaSelecionada = carta.getName();
            SegundaSelecionadaObj = carta;
            
            if(!SegundaSelecionada.equals(PrimeiraSelecionada)){
                
                Path = label.getIcon().toString();
                C2Icon = Path.substring(Path.lastIndexOf("/"  ) + 1);

                System.out.println("Carta 2 Selecionada!");
                carta.setBackground(Color.YELLOW);
                CartasSelecionadas = 0;
                CompararCartas(C1Icon, C2Icon, PrimeiraSelecionada, SegundaSelecionada, PrimeiraSelecionadaObj, SegundaSelecionadaObj);
            }else{
                System.out.println("Não é possível selecionar a mesma carta!");
            }
                        
        }else{
            System.out.println("Você não pode selecionar esta carta!");
        }
    }
    
    static void CompararCartas(String C1Icon, String C2Icon, String PrimeiraSelecionada, String SegundaSelecionada, JPanel PrimeiraCarta, JPanel SegundaCarta){       
        if(C1Icon.equals(C2Icon)){
            System.out.println("Parabéns, você encontrou o par correto! + 10 Pontos");
            Pontos += 10;
            contador_pontos.setText(valueOf(Pontos));
            PrimeiraCarta.setBackground(Color.GREEN);
            SegundaCarta.setBackground(Color.GREEN);
        }else{
            System.out.println("Beeeeeh! Par incorreto, tente novamente!");
            PrimeiraCarta.setBackground(Color.WHITE);
            SegundaCarta.setBackground(Color.WHITE);
        }
    }

}
