/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo_da_memoria;

import java.awt.Color;
import static java.lang.String.valueOf;
import javax.swing.JLabel;
import javax.swing.JPanel;
import static jogo_da_memoria.LayoutFacil.CartasSelecionadas;
import static jogo_da_memoria.LayoutFacil.Path;
import static jogo_da_memoria.LayoutFacil.Pontos;
import static jogo_da_memoria.LayoutFacil.PrimeiraSelecionadaObj;
import static jogo_da_memoria.LayoutFacil.SegundaSelecionadaObj;
import static jogo_da_memoria.LayoutFacil.SelecionarCarta;
import static jogo_da_memoria.LayoutFacil.carta_1;
import static jogo_da_memoria.LayoutFacil.contador_pontos;
import static jogo_da_memoria.LayoutFacil.label_carta_1;

/**
 *
 * @author joaov
 */
public class LayoutMedio extends javax.swing.JFrame {
    public static int CartasSelecionadas = 0;
    public static String Path = "";
    public static String C1Icon = "";
    public static String C2Icon = "";
    public static String SegundaSelecionada = "";
    public static String PrimeiraSelecionada = "";
    public static JPanel SegundaSelecionadaObj;
    public static JPanel PrimeiraSelecionadaObj;
    public static int Pontos = 0;

    /**
     * Creates new form LayoutMedio
     */
    public LayoutMedio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_MenuPrincipal = new javax.swing.JPanel();
        barra_inferior = new javax.swing.JPanel();
        texto_pontos = new javax.swing.JLabel();
        texto_tempo_restante = new javax.swing.JLabel();
        contador_tempo = new javax.swing.JLabel();
        contador_pontos = new javax.swing.JLabel();
        barra_superior = new javax.swing.JPanel();
        texto_barra_superior = new javax.swing.JLabel();
        botao_pause = new javax.swing.JPanel();
        icone_botao_pause = new javax.swing.JLabel();
        carta_1 = new javax.swing.JPanel();
        label_carta_1 = new javax.swing.JLabel();
        carta_2 = new javax.swing.JPanel();
        label_carta_2 = new javax.swing.JLabel();
        carta_3 = new javax.swing.JPanel();
        label_carta_3 = new javax.swing.JLabel();
        carta_4 = new javax.swing.JPanel();
        label_carta_4 = new javax.swing.JLabel();
        carta_5 = new javax.swing.JPanel();
        label_carta_5 = new javax.swing.JLabel();
        carta_6 = new javax.swing.JPanel();
        label_carta_6 = new javax.swing.JLabel();
        carta_7 = new javax.swing.JPanel();
        label_carta_7 = new javax.swing.JLabel();
        carta_8 = new javax.swing.JPanel();
        label_carta_8 = new javax.swing.JLabel();
        carta_9 = new javax.swing.JPanel();
        label_carta_9 = new javax.swing.JLabel();
        carta_10 = new javax.swing.JPanel();
        label_carta_10 = new javax.swing.JLabel();
        carta_11 = new javax.swing.JPanel();
        label_carta_11 = new javax.swing.JLabel();
        carta_12 = new javax.swing.JPanel();
        label_carta_12 = new javax.swing.JLabel();
        carta_13 = new javax.swing.JPanel();
        label_carta_13 = new javax.swing.JLabel();
        carta_14 = new javax.swing.JPanel();
        label_carta_14 = new javax.swing.JLabel();
        carta_15 = new javax.swing.JPanel();
        label_carta_15 = new javax.swing.JLabel();
        carta_16 = new javax.swing.JPanel();
        label_carta_16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 643));

        painel_MenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painel_MenuPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        barra_inferior.setBackground(new java.awt.Color(255, 255, 255));
        barra_inferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        texto_pontos.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        texto_pontos.setForeground(new java.awt.Color(0, 0, 0));
        texto_pontos.setText("Pontos: ");

        texto_tempo_restante.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        texto_tempo_restante.setForeground(new java.awt.Color(0, 0, 0));
        texto_tempo_restante.setText("Tempo restante:");

        contador_tempo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        contador_tempo.setForeground(new java.awt.Color(0, 0, 0));
        contador_tempo.setText("90");

        contador_pontos.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        contador_pontos.setForeground(new java.awt.Color(0, 0, 0));
        contador_pontos.setText("0");

        javax.swing.GroupLayout barra_inferiorLayout = new javax.swing.GroupLayout(barra_inferior);
        barra_inferior.setLayout(barra_inferiorLayout);
        barra_inferiorLayout.setHorizontalGroup(
            barra_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_inferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_pontos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contador_pontos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(texto_tempo_restante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contador_tempo)
                .addGap(123, 123, 123))
        );
        barra_inferiorLayout.setVerticalGroup(
            barra_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(texto_pontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(texto_tempo_restante)
                .addComponent(contador_tempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contador_pontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barra_superior.setBackground(new java.awt.Color(255, 255, 255));
        barra_superior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        barra_superior.setToolTipText("");

        texto_barra_superior.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        texto_barra_superior.setForeground(new java.awt.Color(0, 0, 0));
        texto_barra_superior.setText("Jogo da Memória");

        javax.swing.GroupLayout barra_superiorLayout = new javax.swing.GroupLayout(barra_superior);
        barra_superior.setLayout(barra_superiorLayout);
        barra_superiorLayout.setHorizontalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barra_superiorLayout.setVerticalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texto_barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
        );

        botao_pause.setBackground(new java.awt.Color(255, 255, 255));
        botao_pause.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        botao_pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_pauseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao_pauseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao_pauseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botao_pauseLayout = new javax.swing.GroupLayout(botao_pause);
        botao_pause.setLayout(botao_pauseLayout);
        botao_pauseLayout.setHorizontalGroup(
            botao_pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botao_pauseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icone_botao_pause)
                .addContainerGap())
        );
        botao_pauseLayout.setVerticalGroup(
            botao_pauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botao_pauseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icone_botao_pause)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        carta_1.setBackground(new java.awt.Color(255, 255, 255));
        carta_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_1Layout = new javax.swing.GroupLayout(carta_1);
        carta_1.setLayout(carta_1Layout);
        carta_1Layout.setHorizontalGroup(
            carta_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_1Layout.setVerticalGroup(
            carta_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_2.setBackground(new java.awt.Color(255, 255, 255));
        carta_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_2Layout = new javax.swing.GroupLayout(carta_2);
        carta_2.setLayout(carta_2Layout);
        carta_2Layout.setHorizontalGroup(
            carta_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_2Layout.setVerticalGroup(
            carta_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_3.setBackground(new java.awt.Color(255, 255, 255));
        carta_3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_3Layout = new javax.swing.GroupLayout(carta_3);
        carta_3.setLayout(carta_3Layout);
        carta_3Layout.setHorizontalGroup(
            carta_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_3Layout.setVerticalGroup(
            carta_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_3, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_4.setBackground(new java.awt.Color(255, 255, 255));
        carta_4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_4Layout = new javax.swing.GroupLayout(carta_4);
        carta_4.setLayout(carta_4Layout);
        carta_4Layout.setHorizontalGroup(
            carta_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_4Layout.setVerticalGroup(
            carta_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_5.setBackground(new java.awt.Color(255, 255, 255));
        carta_5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_5Layout = new javax.swing.GroupLayout(carta_5);
        carta_5.setLayout(carta_5Layout);
        carta_5Layout.setHorizontalGroup(
            carta_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_5Layout.setVerticalGroup(
            carta_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_6.setBackground(new java.awt.Color(255, 255, 255));
        carta_6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_6Layout = new javax.swing.GroupLayout(carta_6);
        carta_6.setLayout(carta_6Layout);
        carta_6Layout.setHorizontalGroup(
            carta_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_6Layout.setVerticalGroup(
            carta_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_7.setBackground(new java.awt.Color(255, 255, 255));
        carta_7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_7Layout = new javax.swing.GroupLayout(carta_7);
        carta_7.setLayout(carta_7Layout);
        carta_7Layout.setHorizontalGroup(
            carta_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_7Layout.setVerticalGroup(
            carta_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_8.setBackground(new java.awt.Color(255, 255, 255));
        carta_8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_8Layout = new javax.swing.GroupLayout(carta_8);
        carta_8.setLayout(carta_8Layout);
        carta_8Layout.setHorizontalGroup(
            carta_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_8Layout.setVerticalGroup(
            carta_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_9.setBackground(new java.awt.Color(255, 255, 255));
        carta_9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_9Layout = new javax.swing.GroupLayout(carta_9);
        carta_9.setLayout(carta_9Layout);
        carta_9Layout.setHorizontalGroup(
            carta_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_9Layout.setVerticalGroup(
            carta_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_10.setBackground(new java.awt.Color(255, 255, 255));
        carta_10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_10Layout = new javax.swing.GroupLayout(carta_10);
        carta_10.setLayout(carta_10Layout);
        carta_10Layout.setHorizontalGroup(
            carta_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_10Layout.setVerticalGroup(
            carta_10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_11.setBackground(new java.awt.Color(255, 255, 255));
        carta_11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_11Layout = new javax.swing.GroupLayout(carta_11);
        carta_11.setLayout(carta_11Layout);
        carta_11Layout.setHorizontalGroup(
            carta_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_11Layout.setVerticalGroup(
            carta_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_12.setBackground(new java.awt.Color(255, 255, 255));
        carta_12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_12MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_12Layout = new javax.swing.GroupLayout(carta_12);
        carta_12.setLayout(carta_12Layout);
        carta_12Layout.setHorizontalGroup(
            carta_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_12Layout.setVerticalGroup(
            carta_12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_13.setBackground(new java.awt.Color(255, 255, 255));
        carta_13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_13MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_13Layout = new javax.swing.GroupLayout(carta_13);
        carta_13.setLayout(carta_13Layout);
        carta_13Layout.setHorizontalGroup(
            carta_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_13Layout.setVerticalGroup(
            carta_13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_14.setBackground(new java.awt.Color(255, 255, 255));
        carta_14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_14Layout = new javax.swing.GroupLayout(carta_14);
        carta_14.setLayout(carta_14Layout);
        carta_14Layout.setHorizontalGroup(
            carta_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_14Layout.setVerticalGroup(
            carta_14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_15.setBackground(new java.awt.Color(255, 255, 255));
        carta_15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_15Layout = new javax.swing.GroupLayout(carta_15);
        carta_15.setLayout(carta_15Layout);
        carta_15Layout.setHorizontalGroup(
            carta_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_15Layout.setVerticalGroup(
            carta_15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        carta_16.setBackground(new java.awt.Color(255, 255, 255));
        carta_16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        carta_16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta_16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carta_16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carta_16MouseExited(evt);
            }
        });

        javax.swing.GroupLayout carta_16Layout = new javax.swing.GroupLayout(carta_16);
        carta_16.setLayout(carta_16Layout);
        carta_16Layout.setHorizontalGroup(
            carta_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        carta_16Layout.setVerticalGroup(
            carta_16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_carta_16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painel_MenuPrincipalLayout = new javax.swing.GroupLayout(painel_MenuPrincipal);
        painel_MenuPrincipal.setLayout(painel_MenuPrincipalLayout);
        painel_MenuPrincipalLayout.setHorizontalGroup(
            painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_MenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_pause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(barra_inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(barra_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painel_MenuPrincipalLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        painel_MenuPrincipalLayout.setVerticalGroup(
            painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_MenuPrincipalLayout.createSequentialGroup()
                .addComponent(barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(painel_MenuPrincipalLayout.createSequentialGroup()
                            .addComponent(carta_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(carta_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(carta_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(carta_16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painel_MenuPrincipalLayout.createSequentialGroup()
                            .addComponent(carta_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(carta_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(carta_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(carta_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painel_MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(carta_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(carta_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carta_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(botao_pause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barra_inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_pauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_pauseMouseClicked
        new MenuPause().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botao_pauseMouseClicked

    private void botao_pauseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_pauseMouseEntered
        botao_pause.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_botao_pauseMouseEntered

    private void botao_pauseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_pauseMouseExited
        botao_pause.setBackground(Color.WHITE);
    }//GEN-LAST:event_botao_pauseMouseExited

    private void carta_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_1MouseClicked
        carta_1.setName("carta_1");
        SelecionarCarta(carta_1,label_carta_1);
    }//GEN-LAST:event_carta_1MouseClicked

    private void carta_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_1MouseEntered

    }//GEN-LAST:event_carta_1MouseEntered

    private void carta_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_1MouseExited

    }//GEN-LAST:event_carta_1MouseExited

    private void carta_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_2MouseClicked
        carta_2.setName("carta_2");
        SelecionarCarta(carta_2,label_carta_2);
    }//GEN-LAST:event_carta_2MouseClicked

    private void carta_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_2MouseEntered

    }//GEN-LAST:event_carta_2MouseEntered

    private void carta_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_2MouseExited

    }//GEN-LAST:event_carta_2MouseExited

    private void carta_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_3MouseClicked
        carta_3.setName("carta_3");
        SelecionarCarta(carta_3,label_carta_3);
    }//GEN-LAST:event_carta_3MouseClicked

    private void carta_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_3MouseEntered

    }//GEN-LAST:event_carta_3MouseEntered

    private void carta_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_3MouseExited

    }//GEN-LAST:event_carta_3MouseExited

    private void carta_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_4MouseClicked
        carta_4.setName("carta_4");
        SelecionarCarta(carta_4,label_carta_4);
    }//GEN-LAST:event_carta_4MouseClicked

    private void carta_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_4MouseEntered

    }//GEN-LAST:event_carta_4MouseEntered

    private void carta_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_4MouseExited

    }//GEN-LAST:event_carta_4MouseExited

    private void carta_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_5MouseClicked
        carta_5.setName("carta_5");
        SelecionarCarta(carta_5,label_carta_5);
    }//GEN-LAST:event_carta_5MouseClicked

    private void carta_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_5MouseEntered

    }//GEN-LAST:event_carta_5MouseEntered

    private void carta_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_5MouseExited

    }//GEN-LAST:event_carta_5MouseExited

    private void carta_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_6MouseClicked
        carta_6.setName("carta_6");
        SelecionarCarta(carta_6,label_carta_6);
    }//GEN-LAST:event_carta_6MouseClicked

    private void carta_6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_6MouseEntered

    }//GEN-LAST:event_carta_6MouseEntered

    private void carta_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_6MouseExited

    }//GEN-LAST:event_carta_6MouseExited

    private void carta_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_7MouseClicked
        carta_7.setName("carta_7");
        SelecionarCarta(carta_7,label_carta_7);
    }//GEN-LAST:event_carta_7MouseClicked

    private void carta_7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_7MouseEntered

    }//GEN-LAST:event_carta_7MouseEntered

    private void carta_7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_7MouseExited

    }//GEN-LAST:event_carta_7MouseExited

    private void carta_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_8MouseClicked
        carta_8.setName("carta_8");
        SelecionarCarta(carta_8,label_carta_8);
    }//GEN-LAST:event_carta_8MouseClicked

    private void carta_8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_8MouseEntered

    }//GEN-LAST:event_carta_8MouseEntered

    private void carta_8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_8MouseExited

    }//GEN-LAST:event_carta_8MouseExited

    private void carta_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_9MouseClicked
        carta_9.setName("carta_9");
        SelecionarCarta(carta_9,label_carta_9);
    }//GEN-LAST:event_carta_9MouseClicked

    private void carta_9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_9MouseEntered

    }//GEN-LAST:event_carta_9MouseEntered

    private void carta_9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_9MouseExited

    }//GEN-LAST:event_carta_9MouseExited

    private void carta_10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_10MouseClicked
        carta_10.setName("carta_10");
        SelecionarCarta(carta_10,label_carta_10);
    }//GEN-LAST:event_carta_10MouseClicked

    private void carta_10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_10MouseEntered

    }//GEN-LAST:event_carta_10MouseEntered

    private void carta_10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_10MouseExited
   
    }//GEN-LAST:event_carta_10MouseExited

    private void carta_11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_11MouseClicked
        carta_11.setName("carta_11");
        SelecionarCarta(carta_11,label_carta_11);
    }//GEN-LAST:event_carta_11MouseClicked

    private void carta_11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_11MouseEntered

    }//GEN-LAST:event_carta_11MouseEntered

    private void carta_11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_11MouseExited

    }//GEN-LAST:event_carta_11MouseExited

    private void carta_12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_12MouseClicked
        carta_12.setName("carta_12");
        SelecionarCarta(carta_12,label_carta_12);
    }//GEN-LAST:event_carta_12MouseClicked

    private void carta_12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_12MouseEntered

    }//GEN-LAST:event_carta_12MouseEntered

    private void carta_12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_12MouseExited

    }//GEN-LAST:event_carta_12MouseExited

    private void carta_13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_13MouseClicked
        carta_13.setName("carta_13");
        SelecionarCarta(carta_13,label_carta_13);
    }//GEN-LAST:event_carta_13MouseClicked

    private void carta_13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_13MouseEntered

    }//GEN-LAST:event_carta_13MouseEntered

    private void carta_13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_13MouseExited
  
    }//GEN-LAST:event_carta_13MouseExited

    private void carta_14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_14MouseClicked
        carta_14.setName("carta_14");
        SelecionarCarta(carta_14,label_carta_14);
    }//GEN-LAST:event_carta_14MouseClicked

    private void carta_14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_14MouseEntered
 
    }//GEN-LAST:event_carta_14MouseEntered

    private void carta_14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_14MouseExited
       
    }//GEN-LAST:event_carta_14MouseExited

    private void carta_15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_15MouseClicked
        carta_15.setName("carta_15");
        SelecionarCarta(carta_15,label_carta_15);
    }//GEN-LAST:event_carta_15MouseClicked

    private void carta_15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_15MouseEntered
 
    }//GEN-LAST:event_carta_15MouseEntered

    private void carta_15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_15MouseExited
     
    }//GEN-LAST:event_carta_15MouseExited

    private void carta_16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_16MouseClicked
        carta_16.setName("carta_16");
        SelecionarCarta(carta_16,label_carta_16);
    }//GEN-LAST:event_carta_16MouseClicked

    private void carta_16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_16MouseEntered
     
    }//GEN-LAST:event_carta_16MouseEntered

    private void carta_16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta_16MouseExited
       
    }//GEN-LAST:event_carta_16MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutMedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutMedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra_inferior;
    private javax.swing.JPanel barra_superior;
    private javax.swing.JPanel botao_pause;
    private javax.swing.JPanel carta_1;
    private javax.swing.JPanel carta_10;
    private javax.swing.JPanel carta_11;
    private javax.swing.JPanel carta_12;
    private javax.swing.JPanel carta_13;
    private javax.swing.JPanel carta_14;
    private javax.swing.JPanel carta_15;
    private javax.swing.JPanel carta_16;
    private javax.swing.JPanel carta_2;
    private javax.swing.JPanel carta_3;
    private javax.swing.JPanel carta_4;
    private javax.swing.JPanel carta_5;
    private javax.swing.JPanel carta_6;
    private javax.swing.JPanel carta_7;
    private javax.swing.JPanel carta_8;
    private javax.swing.JPanel carta_9;
    public static javax.swing.JLabel contador_pontos;
    private javax.swing.JLabel contador_tempo;
    private javax.swing.JLabel icone_botao_pause;
    public static javax.swing.JLabel label_carta_1;
    public static javax.swing.JLabel label_carta_10;
    public static javax.swing.JLabel label_carta_11;
    public static javax.swing.JLabel label_carta_12;
    public static javax.swing.JLabel label_carta_13;
    public static javax.swing.JLabel label_carta_14;
    public static javax.swing.JLabel label_carta_15;
    public static javax.swing.JLabel label_carta_16;
    public static javax.swing.JLabel label_carta_2;
    public static javax.swing.JLabel label_carta_3;
    public static javax.swing.JLabel label_carta_4;
    public static javax.swing.JLabel label_carta_5;
    public static javax.swing.JLabel label_carta_6;
    public static javax.swing.JLabel label_carta_7;
    public static javax.swing.JLabel label_carta_8;
    public static javax.swing.JLabel label_carta_9;
    private javax.swing.JPanel painel_MenuPrincipal;
    private javax.swing.JLabel texto_barra_superior;
    private javax.swing.JLabel texto_pontos;
    private javax.swing.JLabel texto_tempo_restante;
    // End of variables declaration//GEN-END:variables
static void SelecionarCarta(JPanel carta,JLabel label){
        String cor_carta = carta.getBackground().toString();
        if(CartasSelecionadas == 0 && cor_carta.equals("java.awt.Color[r=255,g=255,b=255]")){
            
            Path = label.getIcon().toString();
            C1Icon = Path.substring(Path.lastIndexOf("/"  ) + 1);
            
            System.out.println("Carta 1 Selecionada!");
            carta.setBackground(Color.YELLOW);
            CartasSelecionadas ++;
            PrimeiraSelecionada = carta.getName();
            PrimeiraSelecionadaObj = carta;
            
        }else if(CartasSelecionadas == 1 && cor_carta.equals("java.awt.Color[r=255,g=255,b=255]")){
            
            SegundaSelecionada = carta.getName();
            SegundaSelecionadaObj = carta;
            
            if(!SegundaSelecionada.equals(PrimeiraSelecionada)){
                
                Path = label.getIcon().toString();
                C2Icon = Path.substring(Path.lastIndexOf("/"  ) + 1);

                System.out.println("Carta 2 Selecionada!");
                carta.setBackground(Color.YELLOW);
                CartasSelecionadas = 0;
                CompararCartas(C1Icon, C2Icon, PrimeiraSelecionada, SegundaSelecionada, PrimeiraSelecionadaObj, SegundaSelecionadaObj);
            }else{
                System.out.println("Não é possível selecionar a mesma carta!");
            }
                        
        }else{
            System.out.println("Você não pode selecionar esta carta!");
        }
    }
    
    static void CompararCartas(String C1Icon, String C2Icon, String PrimeiraSelecionada, String SegundaSelecionada, JPanel PrimeiraCarta, JPanel SegundaCarta){       
        if(C1Icon.equals(C2Icon)){
            System.out.println("Parabéns, você encontrou o par correto! + 10 Pontos");
            Pontos += 10;
            contador_pontos.setText(valueOf(Pontos));
            PrimeiraCarta.setBackground(Color.GREEN);
            SegundaCarta.setBackground(Color.GREEN);
        }else{
            System.out.println("Beeeeeh! Par incorreto, tente novamente!");
            PrimeiraCarta.setBackground(Color.WHITE);
            SegundaCarta.setBackground(Color.WHITE);
        }
    }
}
